version: "3.4"

x-kafka-env-variables: &kafka-config
  KAFKA_ADDR: kafka:9093
  KAFKA_BATCH_UPLOADED_TOPIC: dev_batch_uploaded
  KAFKA_ASSETS_PREPARED_TOPIC: dev_assets_prepared

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: kafka-streams-zookeeper
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka-streams-kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:9093,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CREATE_TOPICS: "test_topic:3:1"
    depends_on:
      - zookeeper
    volumes:
      - kafka:/kafka
volumes:
  kafka: {}
